"""
SQLAlchemy ORM models for the Exam Platform (SQLite via Flask-SQLAlchemy).

Relational schema
-----------------
  questions           master question bank (the pool every exam deals from)
  exams               shareable exam (the universal entry point)
  exam_questions      full question snapshot dealt to an Exam
  sessions            per-student attempt (each registered student gets one)
  students            candidate registration (1:1 with sessions via UNIQUE FK)
  session_questions   per-attempt dealt-question snapshot (isolated from bank)
  answers             submitted response per question (FK -> sessions)

All timestamps are stored as ISO-8601 strings for compatibility with the
existing templates, which render them directly.
"""

from datetime import datetime, timezone

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Exam(db.Model):
    """
    A shareable exam – the universal entry point.

    One Exam is generated by the host and produces a single reusable link
    (/exam/register/<id>) that ANY number of students can open. Each student
    who registers creates their OWN attempt (a Session) under this Exam, so
    hundreds of students can take the same exam concurrently without
    conflicting with one another.

    * id          -> the token shown in the shareable URL (raw UUID hex)
    * host_email  -> the host who generated this exam
    * config      -> JSON blob (exam_title, time_limit_minutes, ratio,
                     max_capacity, custom_registration_fields,
                     required_fields)
    """

    __tablename__ = "exams"

    id = db.Column(db.String(32), primary_key=True)  # shareable exam token
    host_email = db.Column(db.String(255), nullable=True, index=True)
    config = db.Column(db.JSON, nullable=False, default=dict)
    created_at = db.Column(
        db.String(64),
        nullable=False,
        default=lambda: datetime.now(timezone.utc).isoformat(),
    )

    # Every attempt (Session) that belongs to this exam.
    sessions = db.relationship(
        "Session",
        backref="exam",
        cascade="all, delete-orphan",
    )
    # The full snapshotted question set for this exam (attempts re-sample
    # from this snapshot so each student gets their own random subset).
    exam_questions = db.relationship(
        "ExamQuestion",
        backref="exam",
        order_by="ExamQuestion.position",
        cascade="all, delete-orphan",
    )


class ExamQuestion(db.Model):
    """
    The full question snapshot dealt to an Exam at generation time.

    This isolates an Exam from the master bank: later changes to (or
    deletion of) a bank question can never affect an already-generated exam.
    Each per-student attempt re-samples `ratio` random questions from this
    snapshot into its own SessionQuestion rows.
    """

    __tablename__ = "exam_questions"

    id = db.Column(db.Integer, primary_key=True)
    exam_id = db.Column(
        db.String(32), db.ForeignKey("exams.id"), nullable=False
    )
    position = db.Column(db.Integer, nullable=False)  # 0-based index
    question_id = db.Column(db.String(16), nullable=True)  # original bank id
    type = db.Column(db.String(16), nullable=False, default="mcq")
    text = db.Column(db.Text, nullable=False)
    options = db.Column(db.JSON, nullable=True)  # shuffled (mcq)
    correct_index = db.Column(db.Integer, nullable=True)


class Question(db.Model):
    """Master question bank."""

    __tablename__ = "questions"

    id = db.Column(db.String(16), primary_key=True)  # q_<hex>
    host_email = db.Column(db.String(255), nullable=True, index=True)
    type = db.Column(db.String(16), nullable=False, default="mcq")
    text = db.Column(db.Text, nullable=False)
    options = db.Column(db.JSON, nullable=True)  # list[str] (mcq only)
    correct_index = db.Column(db.Integer, nullable=True)  # mcq only
    created_at = db.Column(
        db.String(64),
        nullable=False,
        default=lambda: datetime.now(timezone.utc).isoformat(),
    )


class Session(db.Model):
    """
    One per-student attempt.

    When a student registers for a shared Exam, a brand-new Session is
    created just for them. It carries its own dealt questions, its own
    deadline/timer, and its own answers — so hundreds of students taking the
    same exam never collide.

    * id          -> the UUID hex that identifies this attempt
    * exam_id     -> the Exam this attempt belongs to (the shareable link)
    * host_email  -> the email of the host who owns the exam (nullable,
                     back-filled for existing rows)
    * config      -> JSON blob with everything configured for this exam
                     (time_limit_minutes, ratio, custom_registration_fields,
                     required_fields)
    """

    __tablename__ = "sessions"

    id = db.Column(db.String(16), primary_key=True)  # session_id (hex)
    exam_id = db.Column(
        db.String(32), db.ForeignKey("exams.id"), nullable=True, index=True
    )
    host_email = db.Column(db.String(255), nullable=True, index=True)
    expiry = db.Column(db.DateTime, nullable=True)
    config = db.Column(db.JSON, nullable=False, default=dict)
    status = db.Column(db.String(16), nullable=False, default="pending")
    started_at = db.Column(db.String(64), nullable=True)
    deadline = db.Column(db.String(64), nullable=True)
    completed_at = db.Column(db.String(64), nullable=True)
    score = db.Column(db.Integer, nullable=True)
    total_selected = db.Column(db.Integer, nullable=True)
    created_at = db.Column(
        db.String(64),
        nullable=False,
        default=lambda: datetime.now(timezone.utc).isoformat(),
    )

    student = db.relationship(
        "Student",
        backref=db.backref("session", uselist=False),
        uselist=False,
        cascade="all, delete-orphan",
    )
    questions = db.relationship(
        "SessionQuestion",
        backref="session",
        order_by="SessionQuestion.position",
        cascade="all, delete-orphan",
    )
    answers = db.relationship(
        "Answer",
        backref="session",
        order_by="Answer.position",
        cascade="all, delete-orphan",
    )


class Student(db.Model):
    """
    Candidate registration.

    The 1:1 link to a session is enforced by a UNIQUE foreign key on
    session_id — the database-level guarantee that two simultaneous
    registrations for the same session cannot both succeed (only one row can
    exist per session).
    """

    __tablename__ = "students"

    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(
        db.String(16),
        db.ForeignKey("sessions.id"),
        unique=True,  # <-- the anti-duplicate-registration constraint
        nullable=False,
    )
    name = db.Column(db.String(200), nullable=False, default="")
    phone = db.Column(db.String(20), nullable=False, default="")
    custom_fields = db.Column(db.JSON, nullable=False, default=dict)
    registered_at = db.Column(db.String(64), nullable=True)
    # Legal disclaimer acceptance — the candidate must tick the mandatory
    # "I Agree" box before the exam starts. Stored per-student so the host
    # has an audit trail that each candidate accepted the liability terms.
    agreed_to_policy = db.Column(db.Boolean, nullable=False, default=False)
    agreed_at = db.Column(db.String(64), nullable=True)


class HostUser(db.Model):
    """
    A registered host / teacher / organizer who may access the dashboard,
    create exams, and review submissions.

    Only users with a valid account + password can reach the /host* routes
    (enforced by the `login_required` decorator in app.py).
    """

    __tablename__ = "host_users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True, nullable=False, index=True)
    name = db.Column(db.String(200), nullable=False, default="")
    password_hash = db.Column(db.String(255), nullable=False)
    created_at = db.Column(
        db.String(64),
        nullable=False,
        default=lambda: datetime.now(timezone.utc).isoformat(),
    )


class OtpToken(db.Model):
    """
    One-time password token used for host password reset.

    A 6-digit code is generated with `secrets` and stored hashed here with a
    short expiry (default 10 minutes). Each token is single-use.
    """

    __tablename__ = "otp_tokens"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), nullable=False, index=True)
    code_hash = db.Column(db.String(255), nullable=False)
    purpose = db.Column(db.String(32), nullable=False, default="reset")
    expires_at = db.Column(db.String(64), nullable=False)
    used = db.Column(db.Boolean, nullable=False, default=False)
    created_at = db.Column(
        db.String(64),
        nullable=False,
        default=lambda: datetime.now(timezone.utc).isoformat(),
    )


class SessionQuestion(db.Model):
    """
    The exact question snapshot dealt to a session.

    This isolates a session from the master bank: later changes to a bank
    question, or even deleting it, can never affect an already-generated
    session. MCQ options are stored in their shuffled order with the
    recomputed correct_index.
    """

    __tablename__ = "session_questions"

    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(
        db.String(16), db.ForeignKey("sessions.id"), nullable=False
    )
    position = db.Column(db.Integer, nullable=False)  # 0-based exam index
    question_id = db.Column(db.String(16), nullable=True)  # original bank id
    type = db.Column(db.String(16), nullable=False, default="mcq")
    text = db.Column(db.Text, nullable=False)
    options = db.Column(db.JSON, nullable=True)  # shuffled (mcq)
    correct_index = db.Column(db.Integer, nullable=True)


class Answer(db.Model):
    """
    One submitted response for one question in a session.

    * response      -> JSON scalar: selected option index (mcq) OR free text
                       (essay / coding)
    * correct       -> True/False for mcq, None for manually-reviewed types
    * correct_index -> the snapshot's correct index (mcq only), kept for the
                       result / details pages
    """

    __tablename__ = "answers"

    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(
        db.String(16), db.ForeignKey("sessions.id"), nullable=False
    )
    position = db.Column(db.Integer, nullable=False)  # matches SessionQuestion
    question_id = db.Column(db.String(16), nullable=True)
    type = db.Column(db.String(16), nullable=False, default="mcq")
    response = db.Column(db.JSON, nullable=True)  # int | str
    correct = db.Column(db.Boolean, nullable=True)
    correct_index = db.Column(db.Integer, nullable=True)


# ---------------------------------------------------------------------------
# Serializers — preserve the EXACT dict shape the templates already consume,
# so the front-end (host.html, exam.html, result.html, details.html + PDFs)
# requires ZERO changes.
# ---------------------------------------------------------------------------


def bank_question_to_dict(q: Question) -> dict:
    return {
        "id": q.id,
        "type": q.type or "mcq",
        "text": q.text,
        "options": q.options,
        "correct_index": q.correct_index,
    }


def exam_question_to_dict(q: ExamQuestion) -> dict:
    return {
        "id": q.question_id or f"pos_{q.position}",
        "type": q.type or "mcq",
        "text": q.text,
        "options": q.options,
        "correct_index": q.correct_index,
    }


def session_question_to_dict(q: SessionQuestion) -> dict:
    return {
        "id": q.question_id or f"pos_{q.position}",
        "type": q.type or "mcq",
        "text": q.text,
        "options": q.options,
        "correct_index": q.correct_index,
    }


def answer_to_graded_dict(a: Answer) -> dict:
    return {
        "type": a.type or "mcq",
        "selected": a.response,
        "correct_index": a.correct_index,
        "correct": a.correct,
    }


def student_to_dict(st: Student) -> dict:
    """Rebuild the legacy ``session['student']`` dict (name, phone, custom…)."""
    data = dict(st.custom_fields or {})
    data["name"] = st.name
    data["phone"] = st.phone
    if st.registered_at:
        data["registered_at"] = st.registered_at
    return data


def session_to_dict(s: Session) -> dict:
    """Rebuild the legacy ``session`` dict consumed by every template."""
    return {
        "session_id": s.id,
        "exam_title": (s.config or {}).get("exam_title", ""),
        "time_limit_minutes": (s.config or {}).get("time_limit_minutes", 30),
        "ratio": (s.config or {}).get("ratio", 0),
        "custom_registration_fields": (s.config or {}).get(
            "custom_registration_fields", []
        ),
        "required_fields": (s.config or {}).get(
            "required_fields", ["name", "phone"]
        ),
        "questions": [session_question_to_dict(q) for q in s.questions],
        "student": student_to_dict(s.student) if s.student else None,
        "status": s.status,
        "started_at": s.started_at,
        "deadline": s.deadline,
        "completed_at": s.completed_at,
        "answers": {str(a.position): a.response for a in s.answers},
        "graded": [answer_to_graded_dict(a) for a in s.answers] or None,
        "score": s.score,
        "total_selected": s.total_selected,
        "created_at": s.created_at,
    }


def exam_to_dict(ex: Exam) -> dict:
    """Serialize an Exam for the host dashboard."""
    cfg = ex.config or {}
    return {
        "exam_id": ex.id,
        "exam_title": cfg.get("exam_title", ""),
        "time_limit_minutes": cfg.get("time_limit_minutes", 30),
        "ratio": cfg.get("ratio", 0),
        "max_capacity": cfg.get("max_capacity", 500),
        "custom_registration_fields": cfg.get(
            "custom_registration_fields", []
        ),
        "required_fields": cfg.get("required_fields", ["name", "phone"]),
        "questions": [exam_question_to_dict(q) for q in ex.exam_questions],
        "created_at": ex.created_at,
        "attempt_count": len(ex.sessions),
        "completed_count": len(
            [s for s in ex.sessions if s.status == "completed"]
        ),
    }
